version: "3"
services:
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
    networks:
      - appnet

  server:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    container_name: docker_server
    environment:
      FABU_DB_HOST: mongo
      FABU_UPLOAD_DIR: /fabu/upload
    ports:
      - "9898:9898"
    volumes:
      - ./upload:/fabu/upload
    depends_on:
      - mongo
    networks:
      - appnet

networks:
  appnet:
    driver: bridge
